[package]
name = "sprite-file-type"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
image = {version="0.25.0"}
serde = {version="1.0.211", features=["derive"]}
serialimage = "4.1.1"
