[package]
name = "sprite-sheet-file-type"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "File Type that simplifies SpriteSheet creation"

[dependencies]
image = {version="0.25.0"}
serde = {version="1.0.213", features=["derive"]}
serde_json = "1.0.132"
